name: GroupExplorer
version: "0.5.0"
date: 2019-05-14
description: |
    Invoking Group Explorer from GAP

authors:
    - name: Nathan Carter
      url: http://nathancarter.github.io

maintainers:
    - name: Nathan Carter
      url: http://nathancarter.github.io

GAP: ">= 4.9"

needed-pkgs:
    - name: "JupyterViz"
      version: "1.5.0"
      url: "https://nathancarter.github.io/jupyterviz"
    - name: "GAPDoc"
      version: "1.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://nathancarter.github.io/groupexplorer
readme: README.md
packageinfo: https://nathancarter.github.io/groupexplorer/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nathancarter/groupexplorer/releases/download/v0.5.0/groupexplorer-0.5.0.tar.gz

abstract: |
    The <span class="pkgname">GroupExplorer</span> package    lets GAP users invoke the web-based app Group Explorer,    for visualizing groups, from within GAP.  It supports    invocation from within Jupyter notebooks or from the GAP    REPL, by leveraging the JupyterViz package.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    groups, visualization, Cayley graph, multiplication table, cycle graph.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Car19</span>]   <b class='BibAuthor'>Carter, N.</b>,
     <i class='BibTitle'>GroupExplorer, Invoking Group Explorer from GAP,
             Version 0.5.0</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://nathancarter.github.io/groupexplorer">https://nathancarter.github.io/groupexplorer</a></span>.
    </p>
    

bibtex: |
    @misc{ GroupExplorer0.5.0,
      author =           {Carter, N.},
      title =            {{GroupExplorer}, Invoking Group Explorer from
                          GAP, {V}ersion 0.5.0},
      month =            {May},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href
                          {https://nathancarter.github.io/groupexplorer}
                          {\texttt{https://nathancarter.github.io/}\discretionary
                          {}{}{}\texttt{groupexplorer}}},
      keywords =         {groups;    visualization;    Cayley    graph;
                          multiplication table; cycle graph},
      printedkey =       {Car19}
    }

